---
title: "ELS.ROI.73N"
output: html_document
---

Relations between Neural Regions and ELS during Anticipation of Gains and Losses
========================================================
```{r load in data}
require(ggplot2)
#setwd("~/Documents/ELS/KIDMID/Analysis/ROI/73N_ELS")
setwd("/Volumes/TUXEDOSAM/73N_ELS/")
a = read.csv("featquery_anticipation09-Feb-2015.csv")
o = read.csv("featquery_outcome09-Feb-2015.csv")
#setwd("~/Documents/ELS/KIDMID/Analysis/behavior")
setwd("/Volumes/TUXEDOSAM/")
b = read.csv("all_behavior_10-Feb-2015.csv")

#removing behavioral outliers
b = b[-c(14,26,33),]  

cor.test(a$Rput_loss,b$ELS.subj)
plot(a$Rcaud_loss,b$ELS.subj)
abline(lm(b$ELS.subj~a$Rcaud_loss))

cor.test(a$Rcaud_loss,b$ELS.subj) #ns

cor.test(a$Rput_loss-a$Rput_nonloss,b$ELS.subj)
plot(a$Rput_loss-a$Rput_nonloss,b$ELS.subj)
abline(lm(b$ELS.subj~(a$Rput_loss-a$Rput_nonloss)))

cor.test(a$Rcaud_loss-a$Rcaud_nonloss,b$ELS.subj)
plot(b$ELS.subj,a$Rcaud_loss-a$Rcaud_nonloss)
abline(lm(a$Rcaud_loss-a$Rcaud_nonloss)~b$ELS.subj)


cor.test(a$Rins_loss - a$Rins_nonloss,b$ELS.subj)
cor.test(a$Lins_loss - a$Lins_nonloss,b$ELS.subj)


d = cbind(b,a) #merge data frames
d2 = d[-c(5,7,31),]
d$gender = factor(d$gender)
d2$gender = factor(d2$gender)
d3$gender = factor(d3$gender)

summary(lm(d$Rput_loss ~ d$ELS.subj + d$v2 + d$gender + d$rt_loss))
summary(lm(d$Rput_loss-d$Rput_nonloss ~ d$ELS.subj + d$v2 + d$gender + d$rt_loss-d$rt_nonloss))
summary(lm(d$Rput_loss-d$Rput_nonloss ~ d$ELS.subjcat2 + d$v2 + d$gender + d$rt_loss-d$rt_nonloss))

summary(lm(d$Ramy_loss-d$Ramy_nonloss ~ d$ELS.subj + d$v1 + d$gender + (d$rt_loss-d$rt_nonloss)))
summary(lm(d$Rput_loss-d$Rput_nonloss ~ d$ELS.subj + d$v2 + d$gender + (d$rt_loss-d$rt_nonloss)))
summary(lm(d$Rput_loss-d$Rput_nonloss ~ d$ELS.subj + d$v2 + d$gender))

summary(lm(d$Rcaud_loss-d$Rcaud_nonloss ~ d$ELS.subj + d$v2 + d$gender + (d$rt_loss-d$rt_nonloss)))
summary(lm(d$Rcaud_loss-d$Rcaud_nonloss ~ poly(d$ELS.subj,2) + d$v2 + d$gender + (d$rt_loss-d$rt_nonloss)))
summary(lm(d$Rcaud_gain-d$Rcaud_nongain ~ (d$ELS.subj * d$gender)  + d$v2))

plot(x=d$ELS.subj,y=d$Rcaud_loss-d$Rcaud_nonloss)
abline(lm(d$Rcaud_loss-d$Rcaud_nonloss ~ d$ELS.subj + d$v2 + d$gender + (d$rt_loss-d$rt_nonloss)))
abline(lm(d$Rcaud_loss-d$Rcaud_nonloss ~ d$ELS.subj))

summary(lm(d$RHipp_loss-d$RHipp_nonloss ~ d$ELS.subj + d$v2 + d$gender + (d$rt_loss-d$rt_nonloss)))
summary(lm(d$RHipp_loss-d$RHipp_nonloss ~ d$ELS.subjcat2 + d$v2 + d$gender + (d$rt_loss-d$rt_nonloss)))
summary(lm(d$Ramy_loss-d$Ramy_nonloss ~ d$ELS.subj + d$v2 + d$gender + (d$rt_loss-d$rt_nonloss)))

#interactions
summary(lm(d$Rput_loss-d$Rput_nonloss ~ (d$ELS.subj * d$gender) + d$v2 + d$rt_loss-d$rt_nonloss))
summary(lm(d$Rcaud_gain-d$Rcaud_nongain ~ (d$ELS.subj * d$gender) + d$v2 + d$rt_gain-d$rt_nongain))
summary(lm(d$Rcaud_loss-d$Rcaud_nonloss ~ (d$ELS.subj * d$gender) + d$v2 + d$rt_loss-d$rt_nonloss))

```

```{r ELS}
#convert ELS from continuous to categorical
summary(d$ELS.subj) 
d$ELS.subjcat1 = cut(d$ELS.subj, c(0,5,10,30), right=FALSE) #3 groups= 0-4, 5-10, 11-30
d$ELS.subjcat2 = cut(d$ELS.subj, c(0,5,10,30), right=FALSE, labels=c("low","int","high")) 
table(d$ELS.subjcat2)

table(d$gender, d$ELS.subjcat2)
chisq.test(d$gender, d$ELS.subjcat2)

table(d$v1, d$ELS.subjcat2)
chisq.test(d$v1, d$ELS.subjcat2)

table(d$v2, d$ELS.subjcat2)
chisq.test(d$v2, d$ELS.subjcat2)

table(d$Grange, d$ELS.subjcat2)
chisq.test(d$Grange, d$ELS.subjcat2)

#accuracy
summary(lm(d$loss_acc ~ d$ELS.subj))
summary(lm(d$loss_acc-d$nonloss_acc ~ d$ELS.subj))

#rt
summary(lm(d$rt_loss ~ d$ELS.subj)) #ns
summary(lm(d$rt_loss-d$rt_nonloss ~ d$ELS.subj)) #p = .004, high ELS p's are slower to loss relative to nonloss cues
qplot(d$ELS.subj,d$rt_loss-d$rt_nonloss)
summary(lm(d$rt_loss-d$rt_nonloss ~ d$ELS.subjcat2)) #p=.04 for high v low.

```


Left caudate
-------------
```{r Lcaud}
##MAIN EFFECTS ONLY
#create dataframe to make bargraphs for main effects 
Lcaud.pe = c(d$Lcaud_gain,d$Lcaud_nongain,d$Lcaud_loss,d$Lcaud_nonloss)
condition.2 = c(rep(x = "gain", times = 73), rep(x = "nongain", times = 73), rep(x = "loss", times = 73), rep(x = "nonloss", times = 73))
Lcaudbar = data.frame(condition.2,Lcaud.pe)

Lcaud.summary = data.frame(
  condition = levels(Lcaudbar$condition.2),
  mean = tapply(Lcaudbar$Lcaud.pe, Lcaudbar$condition, mean),
  n = tapply(Lcaudbar$Lcaud.pe, Lcaudbar$condition, length),
  sd = tapply(Lcaudbar$Lcaud.pe, Lcaudbar$condition, sd)
  )

#calculate standard error of the mean 
Lcaud.summary$sem = Lcaud.summary$sd/sqrt(Lcaud.summary$n) 

#calculate margin of error for CI
alpha = .05 #95% confidence interval
Lcaud.summary$me = qt(1-alpha/2, df = Lcaud.summary$n)*Lcaud.summary$sem

#error bars represent standard error of the mean
g2.SE = ggplot(Lcaud.summary, aes(x = condition, y = mean)) + 
  geom_bar(position = position_dodge(), stat="identity", fill="red", width=.5) +
  geom_errorbar(aes(ymin=mean-sem, ymax=mean+sem), width=.3) +
  labs(x = "Anticipation", y = "Percent BOLD signal change in L Caud") +
  scale_y_continuous(limits=c(-.3, .4)) +
  ggtitle("Anticipatory L Caud Activity") +
  geom_hline(yintercept=0, linetype = 1) +
  theme_bw() +
  theme(panel.grid.major = element_blank())
print(g2.SE)

###ELS EFFECTS
#rearrange data to make bargraphs for ELS and condition effects 
ELScond = c(rep(x=d$ELS.subjcat2, times = 4)) #rep d$ELS.subjcat2 vector 4 times
Lcaudbar.els = data.frame(condition.2,Lcaud.pe,ELScond) #concatenate vectors
Lcaud.means = aggregate(Lcaudbar.els$Lcaud.pe, list(ELS = Lcaudbar.els$ELScond, cond = Lcaudbar.els$condition.2), mean) #sort pe means by condition and ELS cat
Lcaud.sd = aggregate(Lcaudbar.els$Lcaud.pe, list(ELS = Lcaudbar.els$ELScond, cond = Lcaudbar.els$condition.2), sd)
Lcaud.n = aggregate(Lcaudbar.els$Lcaud.pe, list(ELS = Lcaudbar.els$ELScond, cond = Lcaudbar.els$condition.2), length)

Lcaud.summary.els = data.frame(
  Lcaud.means,  #x = mean
  sd = Lcaud.sd[3], #x.1 = sd
  n = Lcaud.n[3]) #x.2 = n

#calculate standard error of the mean 
Lcaud.summary.els$sem = Lcaud.summary.els$x.1/sqrt(Lcaud.summary.els$x.2) 
factor(Lcaud.summary.els$ELS)
Lcaud.summary.els$ELS = c(rep(c("low","int","high"), times = 4))


limits = aes(ymin=x-sem, ymax=x+sem)
g2.ELS = ggplot(Lcaud.summary.els, aes(x = cond, y = x, fill = ELS)) +  
  geom_bar(stat="identity",position=position_dodge(), width = .75) +
  geom_errorbar(limits,position=position_dodge(width=.75), width = .5) +
  labs(x = "Anticipation", y = "% BOLD signal change") +
  scale_y_continuous(limits=c(-.35, .5)) +
  ggtitle("Anticipatory L Caud Activity") +
  geom_hline(yintercept=0, linetype = 1) +
  theme_bw() +
  theme(panel.grid.major = element_blank())
print(g2.ELS)

summary(lm(d$Lcaud_loss-d$Lcaud_nonloss ~ d$ELS.subj + d$v2 + d$gender + d$rt_loss-d$rt_nonloss))
summary(lm(d$Lcaud_loss-d$Lcaud_nonloss ~ d$ELS.subj + d$v2))
summary(lm(d$Lcaud_loss-d$Lcaud_nonloss ~ (d$ELS.subj * d$gender) + d$v2))
cor.test(d$Lcaud_loss-d$Lcaud_nonloss, d$ELS.subj)

#gain v nongain
cor.test(d$Lcaud_gain-d$Lcaud_nongain, d$ELS.subj)
summary(lm(d$Lcaud_gain-d$Lcaud_nongain ~ d$ELS.subj + d$v2))

summary(lm(d$Lcaud_gain-d$Lcaud_nongain ~ poly(d$ELS.subj,2) + d$v2))
summary(lm(d$Lcaud_gain-d$Lcaud_nongain ~ d$ELS.subjcat2 + d$v2))

#success
summary(lm(d$Lcaud_loss-d$Lcaud_nonloss ~ d$ELS.subj + d$total_acc  + d$v2))
summary(lm(d$Lcaud_loss-d$Lcaud_nonloss ~ d$ELS.subj + d$loss_acc-d$nonloss_acc  + d$v2))
```

Right caudate
---------------
```{r Rcaud}
##MAIN EFFECTS ONLY
#create dataframe to make bargraphs
Rcaud.pe = c(a$Rcaud_gain,a$Rcaud_nongain,a$Rcaud_loss,a$Rcaud_nonloss)
condition.2 = c(rep(x = "gain", times = 73), rep(x = "nongain", times = 73), rep(x = "loss", times = 73), rep(x = "nonloss", times = 73))
Rcaudbar = data.frame(condition.2,Rcaud.pe)

Rcaud.summary = data.frame(
  condition = levels(Rcaudbar$condition.2),
  mean = tapply(Rcaudbar$Rcaud.pe, Rcaudbar$condition, mean),
  n = tapply(Rcaudbar$Rcaud.pe, Rcaudbar$condition, length),
  sd = tapply(Rcaudbar$Rcaud.pe, Rcaudbar$condition, sd)
  )

#calculate standard error of the mean 
Rcaud.summary$sem = Rcaud.summary$sd/sqrt(Rcaud.summary$n) 

#calculate margin of error for CI
alpha = .05 #95% confidence interval
Rcaud.summary$me = qt(1-alpha/2, df = Rcaud.summary$n)*Rcaud.summary$sem

#error bars represent standard error of the mean
g1.SE = ggplot(Rcaud.summary, aes(x = condition, y = mean)) + 
  geom_bar(position = position_dodge(), stat="identity", fill="red", width=.5) +
  geom_errorbar(aes(ymin=mean-sem, ymax=mean+sem), width=.3) +
  labs(x = "Anticipation", y = "Percent BOLD signal change in R Caud") +
  ggtitle("Anticipatory R Caud Activity") +
  scale_y_continuous(limits=c(-.3, .4)) +
  geom_hline(yintercept=0, linetype = 1) +
  theme_bw() +
  theme(panel.grid.major = element_blank())
print(g1.SE)

##ELS effects 
Rcaudbar.els = data.frame(condition.2,Rcaud.pe,ELScond) #concatenate vectors
Rcaud.means = aggregate(Rcaudbar.els$Rcaud.pe, list(ELS = Rcaudbar.els$ELScond, cond = Rcaudbar.els$condition.2), mean) #sort pe means by condition and ELS cat
Rcaud.sd = aggregate(Rcaudbar.els$Rcaud.pe, list(ELS = Rcaudbar.els$ELScond, cond = Rcaudbar.els$condition.2), sd)
Rcaud.n = aggregate(Rcaudbar.els$Rcaud.pe, list(ELS = Rcaudbar.els$ELScond, cond = Rcaudbar.els$condition.2), length)

Rcaud.summary.els = data.frame(
  Rcaud.means,  #x = mean
  sd = Rcaud.sd[3], #x.1 = sd
  n = Rcaud.n[3]) #x.2 = n

#calculate standard error of the mean 
Rcaud.summary.els$sem = Rcaud.summary.els$x.1/sqrt(Rcaud.summary.els$x.2) 
factor(Rcaud.summary.els$ELS)
Rcaud.summary.els$ELS = c(rep(c("low","int","high"), times = 4))


limits = aes(ymin=x-sem, ymax=x+sem)
g1.ELS = ggplot(Rcaud.summary.els, aes(x = cond, y = x, fill = ELS)) +  
  geom_bar(stat="identity",position=position_dodge(), width = .75) +
  geom_errorbar(limits,position=position_dodge(width=.75), width = .5) +
  labs(x = "Anticipation", y = "% BOLD signal change") +
  scale_y_continuous(limits=c(-.35, .5)) +
  ggtitle("Anticipatory R Caud Activity") +
  geom_hline(yintercept=0, linetype = 1) +
  theme_bw() +
  theme(panel.grid.major = element_blank())
print(g1.ELS)

summary(lm(d$Rcaud_loss-d$Rcaud_nonloss ~ d$ELS.subj + d$v2 + d$gender + d$rt_loss-d$rt_nonloss))
summary(lm(d$Rcaud_loss-d$Rcaud_nonloss ~ d$ELS.subj + d$v2))
summary(lm(d$Rcaud_loss-d$Rcaud_nonloss ~ (d$ELS.subj * d$gender) + d$v2))
cor.test(d$Rcaud_loss-d$Rcaud_nonloss, d$ELS.subj)

summary(lm(d$Rcaud_loss-d$Rcaud_nonloss ~ d$ELS.subjcat2 + d$v2 + d$gender + d$rt_loss-d$rt_nonloss))

#gain v nongain
cor.test(d$Rcaud_gain-d$Rcaud_nongain, d$ELS.subj)
summary(lm(d$Rcaud_gain-d$Rcaud_nongain ~ (d$ELS.subj * d$gender) + d$v2))
summary(lm(d$Rcaud_gain-d$Rcaud_nongain ~ poly(d$ELS.subj,2) + d$gender + d$v2))
summary(lm(d$Rcaud_gain-d$Rcaud_nongain ~ d$ELS.subjcat2 + d$gender + d$v2))
summary(lm(d$Rcaud_gain ~ d$ELS.subjcat2 + d$gender + d$v2))

#success
summary(lm(d$Rcaud_loss-d$Rcaud_nonloss ~ d$ELS.subj + d$total_acc  + d$v2)) #p = .06 for total_acc
summary(lm(d$Rcaud_loss-d$Rcaud_nonloss ~ d$ELS.subj + d$loss_acc-d$nonloss_acc  + d$v2))

```

Left Putamen
---------------
```{r Lput}
#create dataframe to make bargraphs
Lput.pe = c(a$Lput_gain,a$Lput_nongain,a$Lput_loss,a$Lput_nonloss)
condition.2 = c(rep(x = "gain", times = 73), rep(x = "nongain", times = 73), rep(x = "loss", times = 73), rep(x = "nonloss", times = 73))
Lputbar = data.frame(condition.2,Lput.pe)

Lput.summary = data.frame(
  condition = levels(Lputbar$condition.2),
  mean = tapply(Lputbar$Lput.pe, Lputbar$condition, mean),
  n = tapply(Lputbar$Lput.pe, Lputbar$condition, length),
  sd = tapply(Lputbar$Lput.pe, Lputbar$condition, sd)
  )

#calculate standard error of the mean 
Lput.summary$sem = Lput.summary$sd/sqrt(Lput.summary$n) 

#calculate margin of error for CI
alpha = .05 #95% confidence interval
Lput.summary$me = qt(1-alpha/2, df = Lput.summary$n)*Lput.summary$sem

#error bars represent standard error of the mean
g3.SE = ggplot(Lput.summary, aes(x = condition, y = mean)) + 
  geom_bar(position = position_dodge(), stat="identity", fill="red", width=.5) +
  geom_errorbar(aes(ymin=mean-sem, ymax=mean+sem), width=.3) +
  scale_y_continuous(limits=c(-.3, .4)) +
  labs(x = "Anticipation", y = "Percent BOLD signal change in L Put") +
  ggtitle("Anticipatory L Putamen Activity") +
  geom_hline(yintercept=0, linetype = 1) +
  theme_bw() +
  theme(panel.grid.major = element_blank())
print(g3.SE)


###ELS effects
Lputbar.els = data.frame(condition.2,Lput.pe,ELScond) #concatenate vectors
Lput.means = aggregate(Lputbar.els$Lput.pe, list(ELS = Lputbar.els$ELScond, cond = Lputbar.els$condition.2), mean) #sort pe means by condition and ELS cat
Lput.sd = aggregate(Lputbar.els$Lput.pe, list(ELS = Lputbar.els$ELScond, cond = Lputbar.els$condition.2), sd)
Lput.n = aggregate(Lputbar.els$Lput.pe, list(ELS = Lputbar.els$ELScond, cond = Lputbar.els$condition.2), length)

Lput.summary.els = data.frame(
  Lput.means,  #x = mean
  sd = Lput.sd[3], #x.1 = sd
  n = Lput.n[3]) #x.2 = n

#calculate standard error of the mean 
Lput.summary.els$sem = Lput.summary.els$x.1/sqrt(Lput.summary.els$x.2) 
factor(Lput.summary.els$ELS)
Lput.summary.els$ELS = c(rep(c("low","int","high"), times = 4))


limits = aes(ymin=x-sem, ymax=x+sem)
g3.ELS = ggplot(Lput.summary.els, aes(x = cond, y = x, fill = ELS)) +  
  geom_bar(stat="identity",position=position_dodge(), width = .75) +
  geom_errorbar(limits,position=position_dodge(width=.75), width = .5) +
  labs(x = "Anticipation", y = "% BOLD signal change") +
  scale_y_continuous(limits=c(-.35, .5)) +
  ggtitle("Anticipatory L Put Activity") +
  geom_hline(yintercept=0, linetype = 1) +
  theme_bw() +
  theme(panel.grid.major = element_blank())
print(g3.ELS)

summary(lm(d$Lput_loss-d$Lput_nonloss ~ d$ELS.subj + d$v2 + d$gender + d$rt_loss-d$rt_nonloss))
summary(lm(d$Lput_loss-d$Lput_nonloss ~ d$ELS.subj))
summary(lm(d$Lput_loss-d$Lput_nonloss ~ (d$ELS.subj * d$gender) + d$v2))
cor.test(d$Lput_loss-d$Lput_nonloss, d$ELS.subj)

#gain v nongain
cor.test(d$Lput_gain-d$Lput_nongain, d$ELS.subj)
cor.test(d$Lput_gain-d$Lput_loss, d$ELS.subj)
summary(lm(d$Lput_gain-d$Lput_nongain ~ d$ELS.subj + d$v2))

summary(lm(d$Lput_gain-d$Lput_nongain ~ poly(d$ELS.subj,2) + d$v2))
summary(lm(d$Lput_gain-d$Lput_nongain ~ d$ELS.subj + d$v2))

#success
summary(lm(d$Lput_loss-d$Lput_nonloss ~ d$ELS.subj + d$total_acc  + d$v2)) #p = .09 for total_acc
summary(lm(d$Lput_loss-d$Lput_nonloss ~ d$ELS.subj + d$loss_acc-d$nonloss_acc  + d$v2))
```

Right Putamen
-------------------
```{r Rput}
#create dataframe to make bargraphs
Rput.pe = c(a$Rput_gain,a$Rput_nongain,a$Rput_loss,a$Rput_nonloss)
condition.2 = c(rep(x = "gain", times = 73), rep(x = "nongain", times = 73), rep(x = "loss", times = 73), rep(x = "nonloss", times = 73))
Rputbar = data.frame(condition.2,Rput.pe)

Rput.summary = data.frame(
  condition = levels(Rputbar$condition.2),
  mean = tapply(Rputbar$Rput.pe, Rputbar$condition, mean),
  n = tapply(Rputbar$Rput.pe, Rputbar$condition, length),
  sd = tapply(Rputbar$Rput.pe, Rputbar$condition, sd)
  )

#calculate standard error of the mean 
Rput.summary$sem = Rput.summary$sd/sqrt(Rput.summary$n) 

#calculate margin of error for CI
alpha = .05 #95% confidence interval
Rput.summary$me = qt(1-alpha/2, df = Rput.summary$n)*Rput.summary$sem

#error bars represent standard error of the mean
g4.SE = ggplot(Rput.summary, aes(x = condition, y = mean)) + 
  geom_bar(position = position_dodge(), stat="identity", fill="red", width=.5) +
  geom_errorbar(aes(ymin=mean-sem, ymax=mean+sem), width=.3) +
  labs(x = "Anticipation", y = "Percent BOLD signal change in R Put") +
  ggtitle("Anticipatory R Putamen Activity") +
  scale_y_continuous(limits=c(-.3, .4)) +
  geom_hline(yintercept=0, linetype = 1) +
  theme_bw() +
  theme(panel.grid.major = element_blank())
print(g4.SE)

##ELS effects
Rputbar.els = data.frame(condition.2,Rput.pe,ELScond) #concatenate vectors
Rput.means = aggregate(Rputbar.els$Rput.pe, list(ELS = Rputbar.els$ELScond, cond = Rputbar.els$condition.2), mean) #sort pe means by condition and ELS cat
Rput.sd = aggregate(Rputbar.els$Rput.pe, list(ELS = Rputbar.els$ELScond, cond = Rputbar.els$condition.2), sd)
Rput.n = aggregate(Rputbar.els$Rput.pe, list(ELS = Rputbar.els$ELScond, cond = Rputbar.els$condition.2), length)

Rput.summary.els = data.frame(
  Rput.means,  #x = mean
  sd = Rput.sd[3], #x.1 = sd
  n = Rput.n[3]) #x.2 = n

#calculate standard error of the mean 
Rput.summary.els$sem = Rput.summary.els$x.1/sqrt(Rput.summary.els$x.2) 
factor(Rput.summary.els$ELS)
Rput.summary.els$ELS = c(rep(c("low","int","high"), times = 4))


limits = aes(ymin=x-sem, ymax=x+sem)
g4.ELS = ggplot(Rput.summary.els, aes(x = cond, y = x, fill = ELS)) +  
  geom_bar(stat="identity",position=position_dodge(), width = .75) +
  geom_errorbar(limits,position=position_dodge(width=.75), width = .5) +
  labs(x = "Anticipation", y = "% BOLD signal change") +
  scale_y_continuous(limits=c(-.35, .5)) +
  ggtitle("Anticipatory R Put Activity") +
  geom_hline(yintercept=0, linetype = 1) +
  theme_bw() +
  theme(panel.grid.major = element_blank())
print(g4.ELS)

summary(lm(d$Rput_loss-d$Rput_nonloss ~ d$ELS.subj + d$v2 + d$gender + d$rt_loss-d$rt_nonloss))
summary(lm(d$Rput_loss-d$Rput_nonloss ~ d$ELS.subj))
summary(lm(d$Rput_loss-d$Rput_nonloss ~ (d$ELS.subj * d$gender) + d$v2))
cor.test(d$Rput_loss-d$Rput_nonloss, d$ELS.subj)
plot(d$ELS.subj, d$Rput_loss-d$Rput_nonloss)
abline(lm(d$Rput_loss-d$Rput_nonloss ~ d$ELS.subj))

d$Rputlvnl = d$Rput_loss-d$Rput_nonloss
c1 = ggplot(d, aes(x=ELS.subj, y=Rputlvnl)) + 
    geom_point(size=4) + 
    labs(x = "Subjective Early Life Stress", y = "% BOLD signal change in R Putamen Loss > Nonloss") +
    ggtitle("Anticipatory R Put Activity as a function of ELS") +
    geom_smooth(method=lm)
print(c1)
dev.off()
#without outliers
cor.test(d2$Rput_loss-d2$Rput_nonloss, d2$ELS.subj)
plot(d2$Rput_loss-d2$Rput_nonloss, d2$ELS.subj)

d2$Rputlvnl = d2$Rput_loss-d2$Rput_nonloss
c2 = ggplot(d2, aes(x=ELS.subj, y=Rputlvnl)) + 
    geom_point(size=4) + 
    geom_smooth(method=lm)
print(c2)

#gain v nongain
cor.test(d$Rput_gain-d$Rput_loss, d$ELS.subj)
summary(lm(d$Rput_gain-d$Rput_nongain ~ d$ELS.subj))
summary(lm(d$Rput_gain-d$Rput_nongain ~ d$ELS.subjcat2 + d$gender + d$v2))

#success
summary(lm(d$Rput_loss-d$Rput_nonloss ~ d$ELS.subj + d$total_acc  + d$v2))
summary(lm(d$Rput_loss-d$Rput_nonloss ~ d$ELS.subj + d$loss_acc-d$nonloss_acc  + d$v2))

```

Left Insula
--------------
```{r Lins}
#create dataframe to make bargraphs
Lins.pe = c(a$Lins_gain,a$Lins_nongain,a$Lins_loss,a$Lins_nonloss)
condition.2 = c(rep(x = "gain", times = 73), rep(x = "nongain", times = 73), rep(x = "loss", times = 73), rep(x = "nonloss", times = 73))
Linsbar = data.frame(condition.2,Lins.pe)

Lins.summary = data.frame(
  condition = levels(Linsbar$condition.2),
  mean = tapply(Linsbar$Lins.pe, Linsbar$condition, mean),
  n = tapply(Linsbar$Lins.pe, Linsbar$condition, length),
  sd = tapply(Linsbar$Lins.pe, Linsbar$condition, sd)
  )

#calculate standard error of the mean 
Lins.summary$sem = Lins.summary$sd/sqrt(Lins.summary$n) 

#calculate margin of error for CI
alpha = .05 #95% confidence interval
Lins.summary$me = qt(1-alpha/2, df = Lins.summary$n)*Lins.summary$sem

#error bars represent standard error of the mean
g5.SE = ggplot(Lins.summary, aes(x = condition, y = mean)) + 
  geom_bar(position = position_dodge(), stat="identity", fill="red", width=.5) +
  geom_errorbar(aes(ymin=mean-sem, ymax=mean+sem), width=.3) +
  labs(x = "Anticipation", y = "Percent BOLD signal change in L Ins") +
  ggtitle("Anticipatory L Insula Activity") +
  scale_y_continuous(limits=c(-.3, .4)) +
  geom_hline(yintercept=0, linetype = 1) +
  theme_bw() +
  theme(panel.grid.major = element_blank())
print(g5.SE)

###ELS effects
Linsbar.els = data.frame(condition.2,Lins.pe,ELScond) #concatenate vectors
Lins.means = aggregate(Linsbar.els$Lins.pe, list(ELS = Linsbar.els$ELScond, cond = Linsbar.els$condition.2), mean) #sort pe means by condition and ELS cat
Lins.sd = aggregate(Linsbar.els$Lins.pe, list(ELS = Linsbar.els$ELScond, cond = Linsbar.els$condition.2), sd)
Lins.n = aggregate(Linsbar.els$Lins.pe, list(ELS = Linsbar.els$ELScond, cond = Linsbar.els$condition.2), length)

Lins.summary.els = data.frame(
  Lins.means,  #x = mean
  sd = Lins.sd[3], #x.1 = sd
  n = Lins.n[3]) #x.2 = n

#calculate standard error of the mean 
Lins.summary.els$sem = Lins.summary.els$x.1/sqrt(Lins.summary.els$x.2) 
factor(Lins.summary.els$ELS)
Lins.summary.els$ELS = c(rep(c("low","int","high"), times = 4))


limits = aes(ymin=x-sem, ymax=x+sem)
g5.ELS = ggplot(Lins.summary.els, aes(x = cond, y = x, fill = ELS)) +  
  geom_bar(stat="identity",position=position_dodge(), width = .75) +
  geom_errorbar(limits,position=position_dodge(width=.75), width = .5) +
  labs(x = "Anticipation", y = "% BOLD signal change") +
  scale_y_continuous(limits=c(-.35, .5)) +
  ggtitle("Anticipatory L Ins Activity") +
  geom_hline(yintercept=0, linetype = 1) +
  theme_bw() +
  theme(panel.grid.major = element_blank())
print(g5.ELS)

summary(lm(d$Lins_loss-d$Lins_nonloss ~ d$ELS.subj + d$v2 + d$gender + d$rt_loss-d$rt_nonloss))
summary(lm(d$Lins_loss-d$Lins_nonloss ~ (d$ELS.subj * d$gender) + d$v2))
cor.test(d$Lins_loss-d$Lins_nonloss,d$ELS.subj)

#gain v nongain
cor.test(d$Lins_gain-d$Lins_nongain,d$ELS.subj)
summary(lm(d$Lins_gain-d$Lins_nongain ~ poly(d$ELS.subj,2) + d$v2))

#success
summary(lm(d$Lins_loss-d$Lins_nonloss ~ d$ELS.subjcat2 * d$loss_acc-d$nonloss_acc + d$v2))
```

Right Insula
--------------
```{r Rins}
#create dataframe to make bargraphs
Rins.pe = c(a$Rins_gain,a$Rins_nongain,a$Rins_loss,a$Rins_nonloss)
condition.2 = c(rep(x = "gain", times = 73), rep(x = "nongain", times = 73), rep(x = "loss", times = 73), rep(x = "nonloss", times = 73))
Rinsbar = data.frame(condition.2,Rins.pe)

Rins.summary = data.frame(
  condition = levels(Rinsbar$condition.2),
  mean = tapply(Rinsbar$Rins.pe, Rinsbar$condition, mean),
  n = tapply(Rinsbar$Rins.pe, Rinsbar$condition, length),
  sd = tapply(Rinsbar$Rins.pe, Rinsbar$condition, sd)
  )

#calculate standard error of the mean 
Rins.summary$sem = Rins.summary$sd/sqrt(Rins.summary$n) 

#calculate margin of error for CI
alpha = .05 #95% confidence interval
Rins.summary$me = qt(1-alpha/2, df = Rins.summary$n)*Rins.summary$sem

#error bars represent standard error of the mean
g6.SE = ggplot(Rins.summary, aes(x = condition, y = mean)) + 
  geom_bar(position = position_dodge(), stat="identity", fill="red", width=.5) +
  geom_errorbar(aes(ymin=mean-sem, ymax=mean+sem), width=.3) +
  scale_y_continuous(limits=c(-.3, .4)) +
  labs(x = "Anticipation", y = "Percent BOLD signal change in R Ins") +
  ggtitle("Anticipatory R Insula Activity") +
  geom_hline(yintercept=0, linetype = 1) +
  theme_bw() +
  theme(panel.grid.major = element_blank())
print(g6.SE)

###ELS effects
Rinsbar.els = data.frame(condition.2,Rins.pe,ELScond) #concatenate vectors
Rins.means = aggregate(Rinsbar.els$Rins.pe, list(ELS = Rinsbar.els$ELScond, cond = Rinsbar.els$condition.2), mean) #sort pe means by condition and ELS cat
Rins.sd = aggregate(Rinsbar.els$Rins.pe, list(ELS = Rinsbar.els$ELScond, cond = Rinsbar.els$condition.2), sd)
Rins.n = aggregate(Rinsbar.els$Rins.pe, list(ELS = Rinsbar.els$ELScond, cond = Rinsbar.els$condition.2), length)

Rins.summary.els = data.frame(
  Rins.means,  #x = mean
  sd = Rins.sd[3], #x.1 = sd
  n = Rins.n[3]) #x.2 = n

#calculate standard error of the mean 
Rins.summary.els$sem = Rins.summary.els$x.1/sqrt(Rins.summary.els$x.2) 
factor(Rins.summary.els$ELS)
Rins.summary.els$ELS = c(rep(c("low","int","high"), times = 4))


limits = aes(ymin=x-sem, ymax=x+sem)
g6.ELS = ggplot(Rins.summary.els, aes(x = cond, y = x, fill = ELS)) +  
  geom_bar(stat="identity",position=position_dodge(), width = .75) +
  geom_errorbar(limits,position=position_dodge(width=.75), width = .5) +
  labs(x = "Anticipation", y = "% BOLD signal change") +
  scale_y_continuous(limits=c(-.35, .5)) +
  ggtitle("Anticipatory R Ins Activity") +
  geom_hline(yintercept=0, linetype = 1) +
  theme_bw() +
  theme(panel.grid.major = element_blank())
print(g6.ELS)

summary(lm(d$Rins_loss-d$Rins_nonloss ~ d$ELS.subj + d$v2 + d$gender + d$rt_loss-d$rt_nonloss))
summary(lm(d$Rins_loss-d$Rins_nonloss ~ (d$ELS.subj * d$gender) + d$v2))
cor.test(d$Rins_loss-d$Rins_nonloss,d$ELS.subj)

#without outliers
cor.test(d2$Rins_loss-d2$Rins_nonloss, d2$ELS.subj)
summary(lm(d2$Rins_loss-d2$Rins_nonloss ~ d2$ELS.subj + d2$v2 + d2$gender + d2$rt_loss-d2$rt_nonloss))
plot(d2$Rins_loss-d2$Rins_nonloss, d2$ELS.subj)

d2$Rputlvnl = d2$Rins_loss-d2$Rins_nonloss
c3 = ggplot(d2, aes(x=ELS.subj, y=Rputlvnl)) + 
    geom_point(size=4) + 
    geom_smooth(method=lm)
print(c3)

#gain v nongain
cor.test(d$Rins_gain-d$Rins_nongain,d$ELS.subj)
summary(lm(d$Rins_gain-d$Rins_nongain ~ poly(d$ELS.subj,2) + d$v2))

#success
summary(lm(d$Rins_loss-d$Rins_nonloss ~ d$ELS.subjcat2 * (d$loss_acc-d$nonloss_acc) + d$v2 + d$gender))
```

Right Amygdala
------------------
```{r Ramy}
#create dataframe to make bargraphs
Ramy.pe = c(a$Ramy_gain,a$Ramy_nongain,a$Ramy_loss,a$Ramy_nonloss)
condition.2 = c(rep(x = "gain", times = 73), rep(x = "nongain", times = 73), rep(x = "loss", times = 73), rep(x = "nonloss", times = 73))
Ramybar = data.frame(condition.2,Ramy.pe)

Ramy.summary = data.frame(
  condition = levels(Ramybar$condition.2),
  mean = tapply(Ramybar$Ramy.pe, Ramybar$condition, mean),
  n = tapply(Ramybar$Ramy.pe, Ramybar$condition, length),
  sd = tapply(Ramybar$Ramy.pe, Ramybar$condition, sd)
  )

#calculate standard error of the mean 
Ramy.summary$sem = Ramy.summary$sd/sqrt(Ramy.summary$n) 

#calculate margin of error for CI
alpha = .05 #95% confidence interval
Ramy.summary$me = qt(1-alpha/2, df = Ramy.summary$n)*Ramy.summary$sem

#error bars represent standard error of the mean
g7.SE = ggplot(Ramy.summary, aes(x = condition, y = mean)) + 
  geom_bar(position = position_dodge(), stat="identity", fill="red", width=.5) +
  geom_errorbar(aes(ymin=mean-sem, ymax=mean+sem), width=.3) +
  scale_y_continuous(limits=c(-.3, .4)) +
  labs(x = "Anticipation", y = "Percent BOLD signal change in R Amy") +
  ggtitle("Anticipatory R Amy Activity") +
  geom_hline(yintercept=0, linetype = 1) +
  theme_bw() +
  theme(panel.grid.major = element_blank())
print(g7.SE)

###ELS effects
Ramybar.els = data.frame(condition.2,Ramy.pe,ELScond) #concatenate vectors
Ramy.means = aggregate(Ramybar.els$Ramy.pe, list(ELS = Ramybar.els$ELScond, cond = Ramybar.els$condition.2), mean) #sort pe means by condition and ELS cat
Ramy.sd = aggregate(Ramybar.els$Ramy.pe, list(ELS = Ramybar.els$ELScond, cond = Ramybar.els$condition.2), sd)
Ramy.n = aggregate(Ramybar.els$Ramy.pe, list(ELS = Ramybar.els$ELScond, cond = Ramybar.els$condition.2), length)

Ramy.summary.els = data.frame(
  Ramy.means,  #x = mean
  sd = Ramy.sd[3], #x.1 = sd
  n = Ramy.n[3]) #x.2 = n

#calculate standard error of the mean 
Ramy.summary.els$sem = Ramy.summary.els$x.1/sqrt(Ramy.summary.els$x.2) 
factor(Ramy.summary.els$ELS)
Ramy.summary.els$ELS = c(rep(c("low","int","high"), times = 4))


limits = aes(ymin=x-sem, ymax=x+sem)
g7.ELS = ggplot(Ramy.summary.els, aes(x = cond, y = x, fill = ELS)) +  
  geom_bar(stat="identity",position=position_dodge(), width = .75) +
  geom_errorbar(limits,position=position_dodge(width=.75), width = .5) +
  labs(x = "Anticipation", y = "% BOLD signal change") +
  scale_y_continuous(limits=c(-.35, .5)) +
  ggtitle("Anticipatory R Amy Activity") +
  geom_hline(yintercept=0, linetype = 1) +
  theme_bw() +
  theme(panel.grid.major = element_blank())
print(g7.ELS)

summary(lm(d$Ramy_loss-d$Ramy_nonloss ~ (d$ELS.subj * d$gender) + d$v2))
cor.test(d$Ramy_loss-d$Ramy_nonloss,d$ELS.subj)

#gain v nongain
cor.test(d$Ramy_gain-d$Ramy_nongain,d$ELS.subj)
summary(lm(d$Ramy_gain-d$Ramy_nongain ~ d$ELS.subj))

```


Left Amygdala
------------------
```{r Lamy}
#create dataframe to make bargraphs
Lamy.pe = c(a$Lamy_gain,a$Lamy_nongain,a$Lamy_loss,a$Lamy_nonloss)
condition.2 = c(rep(x = "gain", times = 73), rep(x = "nongain", times = 73), rep(x = "loss", times = 73), rep(x = "nonloss", times = 73))
Lamybar = data.frame(condition.2,Lamy.pe)

Lamy.summary = data.frame(
  condition = levels(Lamybar$condition.2),
  mean = tapply(Lamybar$Lamy.pe, Lamybar$condition, mean),
  n = tapply(Lamybar$Lamy.pe, Lamybar$condition, length),
  sd = tapply(Lamybar$Lamy.pe, Lamybar$condition, sd)
  )

#calculate standard error of the mean 
Lamy.summary$sem = Lamy.summary$sd/sqrt(Lamy.summary$n) 

#calculate margin of error for CI
alpha = .05 #95% confidence interval
Lamy.summary$me = qt(1-alpha/2, df = Lamy.summary$n)*Lamy.summary$sem

#error bars represent standard error of the mean
g8.SE = ggplot(Lamy.summary, aes(x = condition, y = mean)) + 
  geom_bar(position = position_dodge(), stat="identity", fill="red", width=.5) +
  geom_errorbar(aes(ymin=mean-sem, ymax=mean+sem), width=.3) +
  labs(x = "Anticipation", y = "Percent BOLD signal change in L Amy") +
  ggtitle("Anticipatory L Amy Activity") +
  scale_y_continuous(limits=c(-.3, .4)) +
  geom_hline(yintercept=0, linetype = 1) +
  theme_bw() +
  theme(panel.grid.major = element_blank())
print(g8.SE)

###ELS effects
Lamybar.els = data.frame(condition.2,Lamy.pe,ELScond) #concatenate vectors
Lamy.means = aggregate(Lamybar.els$Lamy.pe, list(ELS = Lamybar.els$ELScond, cond = Lamybar.els$condition.2), mean) #sort pe means by condition and ELS cat
Lamy.sd = aggregate(Lamybar.els$Lamy.pe, list(ELS = Lamybar.els$ELScond, cond = Lamybar.els$condition.2), sd)
Lamy.n = aggregate(Lamybar.els$Lamy.pe, list(ELS = Lamybar.els$ELScond, cond = Lamybar.els$condition.2), length)

Lamy.summary.els = data.frame(
  Lamy.means,  #x = mean
  sd = Lamy.sd[3], #x.1 = sd
  n = Lamy.n[3]) #x.2 = n

#calculate standard error of the mean 
Lamy.summary.els$sem = Lamy.summary.els$x.1/sqrt(Lamy.summary.els$x.2) 
factor(Lamy.summary.els$ELS)
Lamy.summary.els$ELS = c(rep(c("low","int","high"), times = 4))


limits = aes(ymin=x-sem, ymax=x+sem)
g8.ELS = ggplot(Lamy.summary.els, aes(x = cond, y = x, fill = ELS)) +  
  geom_bar(stat="identity",position=position_dodge(), width = .75) +
  geom_errorbar(limits,position=position_dodge(width=.75), width = .5) +
  labs(x = "Anticipation", y = "% BOLD signal change") +
  scale_y_continuous(limits=c(-.35, .5)) +
  ggtitle("Anticipatory L Amy Activity") +
  geom_hline(yintercept=0, linetype = 1) +
  theme_bw() +
  theme(panel.grid.major = element_blank())
print(g8.ELS)

summary(lm(d$Lamy_loss-d$Lamy_nonloss ~ d$ELS.subj + d$v2 + d$gender + d$rt_loss-d$rt_nonloss))
summary(lm(d$Lamy_loss-d$Lamy_nonloss ~ (d$ELS.subj * d$gender) + d$v2)) 
cor.test(d$Lamy_loss-d$Lamy_nonloss,d$ELS.subj)

#gain v nongain
cor.test(d$Lamy_gain-d$Lamy_nongain,d$ELS.subj)
summary(lm(d$Lamy_gain-d$Lamy_nongain ~ d$ELS.subj))


```


Right Hippocampus
------------------
```{r RHipp}
#create dataframe to make bargraphs
RHipp.pe = c(a$RHipp_gain,a$RHipp_nongain,a$RHipp_loss,a$RHipp_nonloss)
condition.2 = c(rep(x = "gain", times = 73), rep(x = "nongain", times = 73), rep(x = "loss", times = 73), rep(x = "nonloss", times = 73))
RHippbar = data.frame(condition.2,RHipp.pe)

RHipp.summary = data.frame(
  condition = levels(RHippbar$condition.2),
  mean = tapply(RHippbar$RHipp.pe, RHippbar$condition, mean),
  n = tapply(RHippbar$RHipp.pe, RHippbar$condition, length),
  sd = tapply(RHippbar$RHipp.pe, RHippbar$condition, sd)
  )

#calculate standard error of the mean 
RHipp.summary$sem = RHipp.summary$sd/sqrt(RHipp.summary$n) 

#calculate margin of error for CI
alpha = .05 #95% confidence interval
RHipp.summary$me = qt(1-alpha/2, df = RHipp.summary$n)*RHipp.summary$sem

#error bars represent standard error of the mean
g9.SE = ggplot(RHipp.summary, aes(x = condition, y = mean)) + 
  geom_bar(position = position_dodge(), stat="identity", fill="red", width=.5) +
  geom_errorbar(aes(ymin=mean-sem, ymax=mean+sem), width=.3) +
  labs(x = "Anticipation", y = "Percent BOLD signal change in R Hipp") +
  ggtitle("Anticipatory R Hipp Activity") +
  scale_y_continuous(limits=c(-.3, .4)) +
  geom_hline(yintercept=0, linetype = 1) +
  theme_bw() +
  theme(panel.grid.major = element_blank())
print(g9.SE)

##ELS effects
RHippbar.els = data.frame(condition.2,RHipp.pe,ELScond) #concatenate vectors
RHipp.means = aggregate(RHippbar.els$RHipp.pe, list(ELS = RHippbar.els$ELScond, cond = RHippbar.els$condition.2), mean) #sort pe means by condition and ELS cat
RHipp.sd = aggregate(RHippbar.els$RHipp.pe, list(ELS = RHippbar.els$ELScond, cond = RHippbar.els$condition.2), sd)
RHipp.n = aggregate(RHippbar.els$RHipp.pe, list(ELS = RHippbar.els$ELScond, cond = RHippbar.els$condition.2), length)

RHipp.summary.els = data.frame(
  RHipp.means,  #x = mean
  sd = RHipp.sd[3], #x.1 = sd
  n = RHipp.n[3]) #x.2 = n

#calculate standard error of the mean 
RHipp.summary.els$sem = RHipp.summary.els$x.1/sqrt(RHipp.summary.els$x.2) 
factor(RHipp.summary.els$ELS)
RHipp.summary.els$ELS = c(rep(c("low","int","high"), times = 4))


limits = aes(ymin=x-sem, ymax=x+sem)
g9.ELS = ggplot(RHipp.summary.els, aes(x = cond, y = x, fill = ELS)) +  
  geom_bar(stat="identity",position=position_dodge(), width = .75) +
  geom_errorbar(limits,position=position_dodge(width=.75), width = .5) +
  labs(x = "Anticipation", y = "% BOLD signal change") +
  scale_y_continuous(limits=c(-.35, .5)) +
  ggtitle("Anticipatory R Hipp Activity") +
  geom_hline(yintercept=0, linetype = 1) +
  theme_bw() +
  theme(panel.grid.major = element_blank())
print(g9.ELS)

summary(lm(d$RHipp_loss-d$RHipp_nonloss ~ d$ELS.subj + d$v2 + d$gender + d$rt_loss-d$rt_nonloss))
summary(lm(d$RHipp_loss-d$RHipp_nonloss ~ (d$ELS.subj * d$gender) + d$v2))
summary(lm(d$RHipp_loss-d$RHipp_nonloss ~ d$ELS.subj + d$v2))
cor.test(d$RHipp_loss-d$RHipp_nonloss,d$ELS.subj)

#gain v nongain
cor.test(d$RHipp_gain-d$RHipp_nongain,d$ELS.subj)
summary(lm(d$RHipp_gain-d$RHipp_nongain ~ d$ELS.subj))
```


Right Pallidum
---------------
```{r Rpall}
#create dataframe to make bargraphs
Rpall.pe = c(a$Rpall_gain,a$Rpall_nongain,a$Rpall_loss,a$Rpall_nonloss)
condition.2 = c(rep(x = "gain", times = 73), rep(x = "nongain", times = 73), rep(x = "loss", times = 73), rep(x = "nonloss", times = 73))
Rpallbar = data.frame(condition.2,Rpall.pe)

Rpall.summary = data.frame(
  condition = levels(Rpallbar$condition.2),
  mean = tapply(Rpallbar$Rpall.pe, Rpallbar$condition, mean),
  n = tapply(Rpallbar$Rpall.pe, Rpallbar$condition, length),
  sd = tapply(Rpallbar$Rpall.pe, Rpallbar$condition, sd)
  )

#calculate standard error of the mean 
Rpall.summary$sem = Rpall.summary$sd/sqrt(Rpall.summary$n) 

#calculate margin of error for CI
alpha = .05 #95% confidence interval
Rpall.summary$me = qt(1-alpha/2, df = Rpall.summary$n)*Rpall.summary$sem

#error bars represent standard error of the mean
g10.SE = ggplot(Rpall.summary, aes(x = condition, y = mean)) + 
  geom_bar(position = position_dodge(), stat="identity", fill="red", width=.5) +
  geom_errorbar(aes(ymin=mean-sem, ymax=mean+sem), width=.3) +
  labs(x = "Anticipation", y = "Percent BOLD signal change in R Pall") +
  ggtitle("Anticipatory R Pall Activity") +
  scale_y_continuous(limits=c(-.3, .4)) +
  geom_hline(yintercept=0, linetype = 1) +
  theme_bw() +
  theme(panel.grid.major = element_blank())
print(g10.SE)

###ELS effects
RPallbar.els = data.frame(condition.2,Rpall.pe,ELScond) #concatenate vectors
RPall.means = aggregate(RPallbar.els$Rpall.pe, list(ELS = RPallbar.els$ELScond, cond = RPallbar.els$condition.2), mean) #sort pe means by condition and ELS cat
RPall.sd = aggregate(RPallbar.els$Rpall.pe, list(ELS = RPallbar.els$ELScond, cond = RPallbar.els$condition.2), sd)
RPall.n = aggregate(RPallbar.els$Rpall.pe, list(ELS = RPallbar.els$ELScond, cond = RPallbar.els$condition.2), length)

RPall.summary.els = data.frame(
  RPall.means,  #x = mean
  sd = RPall.sd[3], #x.1 = sd
  n = RPall.n[3]) #x.2 = n

#calculate standard error of the mean 
RPall.summary.els$sem = RPall.summary.els$x.1/sqrt(RPall.summary.els$x.2) 
factor(RPall.summary.els$ELS)
RPall.summary.els$ELS = c(rep(c("low","int","high"), times = 4))


limits = aes(ymin=x-sem, ymax=x+sem)
g10.ELS = ggplot(RPall.summary.els, aes(x = cond, y = x, fill = ELS)) +  
  geom_bar(stat="identity",position=position_dodge(), width = .75) +
  geom_errorbar(limits,position=position_dodge(width=.75), width = .5) +
  labs(x = "Anticipation", y = "% BOLD signal change") +
  scale_y_continuous(limits=c(-.35, .5)) +
  ggtitle("Anticipatory R Pall Activity") +
  geom_hline(yintercept=0, linetype = 1) +
  theme_bw() +
  theme(panel.grid.major = element_blank())
print(g10.ELS)

summary(lm(d$Rpall_loss-d$Rpall_nonloss ~ d$ELS.subj + d$v2 + d$gender + d$rt_loss-d$rt_nonloss + d$Grange))
summary(lm(d$Rpall_loss-d$Rpall_nonloss ~ d$ELS.subj + d$v2 + d$gender))
summary(lm(d$Rpall_loss-d$Rpall_nonloss ~ (d$ELS.subj + d$gender) + d$v2))
cor.test(d$Rpall_loss-d$Rpall_nonloss, d$ELS.subj)

#gain v nongain
cor.test(d$Rpall_gain-d$Rpall_nongain, d$ELS.subj)
summary(lm(d$Rpall_gain-d$Rpall_nongain ~ poly(d$ELS.subj,2)))

#success
cor.test(d$Rpall_gain-d$Rpall_nongain, d$loss_acc-d$nonloss_acc)
summary(lm(d$Rpall_loss-d$Rpall_nonloss ~ d$ELS.subj + (d$loss_acc-d$nonloss_acc) + d$v2 + d$gender))

```

```{r multiplot function}
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  require(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}

```

```{r subplot}

multiplot(g1.SE, g2.SE, g3.SE, g4.SE, g5.SE, g6.SE, g7.SE, g8.SE, g9.SE, g10.SE, cols=5)

multiplot(g1.ELS, g2.ELS, g3.ELS, g4.ELS, cols=2)
multiplot(g5.ELS, g6.ELS, g7.ELS, g8.ELS, g9.ELS, g10.ELS, cols=3)

```
